### PR TITLE
Testing with Karma, Mocha, Chai, Sinon

### PR DESCRIPTION
**Pull request by milafrerichs**
## What does this PR do?
Introduces javascript testing with [karma](http://karma-runner.github.io/0.12/index.html) (Test Runner), [Mocha](http://mochajs.org/) (JS Test Framework), [Chai](http://chaijs.com) (BDD/TDD assertion lib), [Sinon](http://sinonjs.org) (stubbing, mocking framework)

Adds first test for [validation factory](https://github.com/pudo/spendb/blob/master/spendb/static/js/services.js#L32)
## How to test locally
- Install all dependencies with `npm install`
- run tests with `karma start`

### CODE REVIEW

**Comment by pudo** [comment]
That looks fabulous, I'm very excited about getting rolling on making more tests! I wonder if, before that, it would make sense to at least pull the JS app out of it's hiding place in ``spendb/static`` into the project root, eg. ``spendb.ui``? Just feels odd to have one of the largest parts of the app stowed away in an obscure subdirectory.

**Comment by milafrerichs** [comment]
sure why not. or do you want to split it out into it's own application? (as discussed here #15)
do you want to create an org to include the different modules?

**Comment by milafrerichs** [comment]
@pudo moved everything to spendb.ui as discussed.
hope I did not forget something. the app frontend is working on my docker dev env.
can you try it out?

**Comment by pudo** [comment]
Wooohooo, let me test this locally :) Thanks --

**Comment by pudo** [comment]
Ok, this works for me. I agree that in the medium term we might want to have two repos, but already now I feel it leaves us in a much cleaner state than before. Any reason you see not to merge?

**Comment by milafrerichs** [comment]
nope looks good to me. now that we have the travis tests working as well.

**Pull request merged**
